# <--------------------- Testing Route 1 ---------------------- > 
# POST http://localhost:5000/api/auth/createuser
# Content-Type: application/json

# // body
# {
#   "name" : "hamza",
#   "email" : "hamza124@gmail.com",
#   "password" : "12345"
# }


# <--------------------- Testing Route 2 ---------------------- > 
# POST http://localhost:5000/api/auth/login
# Content-Type: application/json

# // body
# {
#   "email" : "hamza124@gmail.com",
#   "password" : "12345"
# }


# <--------------------- Testing Route 3 ---------------------- > 
# POST http://localhost:5000/api/auth/getuser
# Content-Type: application/json
# auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNmE3Mzk2ZGRlZDg4OTFmMzk0ZDkzNjk2In0sImlhdCI6MTc4NTk2MDgwOX0.4bISNlhG0-ohsFXWr_xrcLrmcbdzOYV9KrV7jKSNGOk

# // body
# {

# }
